### ISSUE TITLE
iOS 10.0.2 redirection issue.

### ISSUE THREAD

**Issue by devgmstudios** [gderosa/coova-chilli#1]
On coova.html - for some strange reason it will not redirect properly to authenticate for iOS 10.0.x devices.
I've tested on iPad & iPhone both.

I've confirmed it works fine on previous versions however.

**Comment by gderosa** [comment]
Hey @devgmstudios this is a fork I created something like 4 years ago... you should probably go here: https://github.com/coova/coova-chilli.

**Comment by devgmstudios** [comment]
Ah, totally just found that.
Thank you very much Guido De Rosa!

Are you still working with this tech? I am dying here - will pay for
consulting or help to debug this issue.
I have a little over 100 routers out in circulation, and this iOS 10 issue
is killing me and not allowing anyone with iOS 10 to connect!

-DJ Akers

**Comment by gderosa** [comment]
Uhm, not really... I worked on this during my previous job... and as you can see I didn't modify much compared to the upstream version... so if you just found a bug, report that to upstream (again, [here](https://github.com/coova/coova-chilli)). If you want some consulting commercially, maybe I can check with my contacts, I'm not sure though but I can try.

**Comment by devgmstudios** [comment]
Excellent thank you for your response Guido!
What are you working on now if you don't mind my asking!

-DJ Akers

**Comment by gderosa** [comment]
Well, you can connect [here](https://www.linkedin.com/in/guidoderosa), if you like... :) Thanks!
